# @package audio_t

_target_: "conette.transforms.get.get_resample_mean_convnext"

src_sr: ???
tgt_sr: 32000
mean_dim: 0

device: "cuda_if_available"
transpose_frame_embs: true
only_frame_embs: false
pretrain_path: "cnext_bl"
