# @package audio_t

_target_: "conette.transforms.get.get_resample_mean_cnn14"

src_sr: ???
tgt_sr: 32000
mean_dim: 0
window_size: 1024
hop_size: 320
mel_bins: 64
device: "cuda_if_available"
transpose_frame_embs: true
only_frame_embs: false

pretrain_path: ???
