# @package audio_t

_target_: "conette.transforms.audio.spec_aug.SpecAugment"

# Note: input must be (bsize, n_channels, time_steps, freq_steps) or (n_channels, time_steps, freq_steps)

time_max_width: 2
time_stripes_num: 2
freq_max_width: 2
freq_stripes_num: 2
time_dim: -2
freq_dim: -1
p: 1.0
