# @package pl

_target_: "conette.pl_modules.conette.CoNeTTEPLM"

task_mode: "ds_src"
task_names: [clotho, audiocaps, macs, wavcaps_audioset_sl, wavcaps_bbc_sound_effects, wavcaps_freesound, wavcaps_soundbible]
gen_test_cands: "generate"
# Model params
label_smoothing: 0.1
gen_val_cands: "none"
mixup_alpha: 0.4
# Encoder params
proj_name: "lin768"
# Decoder params
nhead: 8
d_model: 256
num_decoder_layers: 6
decoder_dropout_p: 0.2
dim_feedforward: 2048
acti_name: "gelu"
# Generate params
min_pred_size: 3
max_pred_size: 30
beam_size: 2
# Optimizer params
optim_name: "AdamW"
lr: 0.0005
weight_decay: 2.0
betas: [0.9, 0.999]
eps: 1e-8
use_custom_wd: true
# Scheduler params
sched_name: "cos_decay"
sched_n_steps: ${trainer.max_epochs}
sched_interval: "epoch"
# Other params
verbose: ${verbose}
