# Template: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CoNeTTE inference

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

# Cancel workflow if a new push occurs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]

    defaults:
      run:
        shell: bash -el {0}

    steps:
    # --- INSTALLATIONS ---
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install uv and set Python ${{ matrix.python-version }}
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true
        cache-dependency-glob: "pyproject.toml"

    - name: Install the project
      run: |
        uv sync --extra dev --extra test

    - name: Install soundfile
      run: |
        # For soundfile dep
        sudo apt-get install libsndfile1

    # --- TESTS ---
    - name: Print install info
      run: |
        uv run conette-info

    - name: Run CoNeTTE predict command line
      run: |
        uv run conette-predict --audio src/conette/data/sample.wav

    - name: Run CoNeTTE unittests
      run: |
        uv run python -m pytest -v
