# Template: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CoNeTTE training

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

env:
  CACHE_NUMBER: 0  # increase to reset cache manually
  DATAROOT: "$HOME/.cache/data"

# Cancel workflow if a new push occurs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]

    defaults:
      run:
        shell: bash -el {0}

    steps:
    # --- INSTALLATIONS ---
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install soundfile
      run: |
        # For soundfile dep
        sudo apt-get install libsndfile1

    - name: Install local packages
      run: |
        python -m pip install -e .[train]

    - name: Load dot cache
      uses: actions/cache@master
      id: cache_dot_cache
      with:
        path: "~/.cache"
        key: ${{ runner.os }}-cache
        restore-keys: |
          ${{ runner.os }}-cache

    - name: Prepare data
      if: steps.cache_dot_cache.outputs.cache-hit != 'true'
      run: |
        cnext_bl_path="$HOME/.cache/torch/hub/checkpoints/convnext_tiny_465mAP_BL_AC_70kit.pth"
        conette-prepare data=clotho default=true pann=false pack_to_hdf=true data.clean_archives=true data.subsets=[val] audio_t.src_sr=44100 audio_t.pretrain_path=${cnext_bl_path} post_hdf_name=bl pretag=cnext_bl csum_in_hdf_name=false path.data=$DATAROOT

    # --- TESTS ---
    - name: Print install info
      run: |
        conette-info

    - name: Train a model
      run: |
        target_hdf="clotho_val_resample_mean_convnext_ident_bl.hdf"
        conette-train pl=baseline trainer=lim2 expt=clotho_cnext_bl dm.train_hdfs=${target_hdf} dm.val_hdfs=${target_hdf} dm.test_hdfs=${target_hdf} dm.predict_hdfs=[] trainer.accelerator=cpu enable_dspeed=false path.data=$DATAROOT
