# Template: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CoNeTTE training

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

# Cancel workflow if a new push occurs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]

    defaults:
      run:
        shell: bash -el {0}

    steps:
    # --- INSTALLATIONS ---
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install soundfile
      run: |
        # For soundfile dep
        sudo apt-get install libsndfile1

    - name: Install local packages
      run: |
        python -m pip install -e .[dev,train]

    - name: Prepare data
      run: |
        conette-prepare data=clotho default=true pann=false pack_to_hdf=true data.clean_archives=true

    # --- TESTS ---
    - name: Print install info
      run: |
        conette-info

    - name: Train a model
      run: |
        conette-train pl=baseline trainer=lim2 expt=clotho_cnext_bl dm.test_hdfs=[clotho_val_resample_mean_convnext_ident_767_bl.hdf,clotho_eval_resample_mean_convnext_ident_767_bl.hdf]
